"""
regtrace.models.evidence
~~~~~~~~~~~~~~~~~~~~~~~~
Minimal generic evidence representation.

A Fact records one observed truth about a single named entity:
  - whether a condition held (condition_name + held)
  - whether an action occurred (action_name + occurred)
  - optional sequence number for ordering within a verification run
  - optional source location (filename + lineno) for call-site traceability

No domain-specific fields. All semantics live in the names.
"""
from __future__ import annotations

from pydantic import BaseModel


class Fact(BaseModel):
    """
    One observed fact in a verification run.

    Exactly one of the following usage patterns applies per Fact:

    Condition fact:
        condition_name = "explicit_consent"
        condition_held = True | False
        action_name    = None
        action_occurred = None

    Action fact:
        action_name     = "external_personal_data_export"
        action_occurred = True
        condition_name  = None
        condition_held  = None

    `seq` is an optional integer ordering. Lower seq = earlier in time.
    When seq is absent, ordering is undefined.

    `filename` and `lineno` are optional source-location fields, set by the
    matcher when analysing static code facts so that counterexamples can
    identify the exact call site.
    """
    condition_name: str | None = None
    condition_held: bool | None = None
    action_name: str | None = None
    action_occurred: bool | None = None
    seq: int | None = None
    # Source location — set by matcher for call-site facts
    filename: str | None = None
    lineno: int | None = None
    # Code identifier at this call site (e.g. "crm.send")
    code_identifier: str | None = None

    def is_condition_fact(self) -> bool:
        return self.condition_name is not None and self.condition_held is not None

    def is_action_fact(self) -> bool:
        return self.action_name is not None and self.action_occurred is True


class Evidence(BaseModel):
    """
    A collection of Facts submitted for a single constraint evaluation.
    The evaluator reads only this; no HTTP, OTel, or Semgrep at this layer.
    """
    constraint_id: str
    facts: list[Fact]


class Counterexample(BaseModel):
    """
    Structured explanation of why a constraint FAILED.

    Includes:
    - constraint and policy identity
    - semantic names (condition_name, action_name)
    - source location of the violating call site when available
    - deterministic fix_context generated by the evaluator
    """
    constraint_id: str
    policy_id: str = ""
    policy_title: str = ""
    condition_name: str
    action_name: str
    observed: str        # human-readable description of what happened
    expected: str        # human-readable description of what should have happened
    # Source location of the violating call site
    filename: str | None = None
    lineno: int | None = None
    code_identifier: str | None = None   # e.g. "crm.send"
    condition_alias: str | None = None   # the matched condition alias if any
    fix_context: str = ""
    evidence: Evidence
